var _pieceSize = "7%,7%";
triviadata={
    baseUrl: "../../src/",
    gameName: "a chess",
	
	boardImage: "../chess/imgs/chess-hex-board1.png",
	boardSize: "640,640",
	helpHtml: "help.html",
	
	categories: [], 

	pieces: [
         {name: "black-tower", code: "image('../chess/imgs/black-tower.png', 10, 10, 74, 74)"},
         {name: "black-knight", code: "image('../chess/imgs/black-knight.png', 10, 10, 74, 74)"},
         {name: "black-bishop", code: "image('../chess/imgs/black-bishop.png', 10, 10, 74, 74)"},
         {name: "black-queen", code: "image('../chess/imgs/black-queen.png', 10, 10, 74, 74)"},
         {name: "black-king", code: "image('../chess/imgs/black-king.png', 10, 10, 74, 74)"},
         {name: "black-pawn", code: "image('../chess/imgs/black-pawn.png', 10, 10, 74, 74)"},
         
         {name: "white-tower", code: "image('../chess/imgs/white-tower.png', 10, 10, 74, 74)"},
         {name: "white-knight", code: "image('../chess/imgs/white-knight.png', 10, 10, 74, 74)"},
         {name: "white-bishop", code: "image('../chess/imgs/white-bishop.png', 10, 10, 74, 74)"},
         {name: "white-queen", code: "image('../chess/imgs/white-queen.png', 10, 10, 74, 74)"},
         {name: "white-king", code: "image('../chess/imgs/white-king.png', 10, 10, 74, 74)"},
         {name: "white-pawn", code: "image('../chess/imgs/white-pawn.png', 10, 10, 74, 74)"},
         
//		{name: "red-tower", code: "image('../chess/imgs/red-tower.png', 10, 10, 74, 74)"},
//		{name: "red-knight", code: "image('../chess/imgs/red-knight.png', 10, 10, 74, 74)"},
//		{name: "red-bishop", code: "image('../chess/imgs/red-bishop.png', 10, 10, 74, 74)"},
//		{name: "red-queen", code: "image('../chess/imgs/red-queen.png', 10, 10, 74, 74)"},
//		{name: "red-king", code: "image('../chess/imgs/red-king.png', 10, 10, 74, 74)"},
//		{name: "red-pawn", code: "image('../chess/imgs/red-pawn.png', 10, 10, 74, 74)"},
	],
	
	addPieces : [{name: "black-tower", position: "20%,13%", size: "8%,8%", color: "black-tower"},
{name: "black-tower", position: "69%,13%", size: "8%,8%", color: "black-tower"},
{name: "black-bishop", position: "44%,17%", size: "8%,8%", color: "black-bishop"},
{name: "black-bishop", position: "44%,9%", size: "8%,8%", color: "black-bishop"},
{name: "black-bishop", position: "44%,1%", size: "8%,8%", color: "black-bishop"},
{name: "black-pawn", position: "53%,29%", size: "8%,8%", color: "black-pawn"},
{name: "black-pawn", position: "44%,34%", size: "8%,8%", color: "black-pawn"},
{name: "black-pawn", position: "36%,29%", size: "8%,8%", color: "black-pawn"},
{name: "black-pawn", position: "28%,25%", size: "8%,8%", color: "black-pawn"},
{name: "black-pawn", position: "20%,21%", size: "8%,8%", color: "black-pawn"},
{name: "black-pawn", position: "11%,17%", size: "8%,8%", color: "black-pawn"},
{name: "black-pawn", position: "77%,17%", size: "8%,8%", color: "black-pawn"},
{name: "black-pawn", position: "69%,21%", size: "8%,8%", color: "black-pawn"},
{name: "black-pawn", position: "61%,25%", size: "8%,8%", color: "black-pawn"},
{name: "black-knight", position: "61%,9%", size: "8%,8%", color: "black-knight"},
{name: "black-knight", position: "28%,8%", size: "8%,8%", color: "black-knight"},
{name: "black-queen", position: "36%,4%", size: "8%,8%", color: "black-queen"},
{name: "black-king", position: "53%,4%", size: "8%,8%", color: "black-king"},
{name: "white-tower", position: "69%,72%", size: "8%,8%", color: "white-tower"},
{name: "white-tower", position: "20%,72%", size: "8%,8%", color: "white-tower"},
{name: "white-knight", position: "61%,76%", size: "8%,8%", color: "white-knight"},
{name: "white-knight", position: "28%,77%", size: "8%,8%", color: "white-knight"},
{name: "white-bishop", position: "44%,68%", size: "8%,8%", color: "white-bishop"},
{name: "white-bishop", position: "45%,76%", size: "8%,8%", color: "white-bishop"},
{name: "white-bishop", position: "44%,85%", size: "8%,8%", color: "white-bishop"},
{name: "white-queen", position: "36%,80%", size: "8%,8%", color: "white-queen"},
{name: "white-king", position: "53%,81%", size: "8%,8%", color: "white-king"},
{name: "white-pawn", position: "77%,68%", size: "8%,8%", color: "white-pawn"},
{name: "white-pawn", position: "69%,63%", size: "8%,8%", color: "white-pawn"},
{name: "white-pawn", position: "61%,59%", size: "8%,8%", color: "white-pawn"},
{name: "white-pawn", position: "53%,55%", size: "8%,8%", color: "white-pawn"},
{name: "white-pawn", position: "45%,51%", size: "8%,8%", color: "white-pawn"},
{name: "white-pawn", position: "36%,55%", size: "8%,8%", color: "white-pawn"},
{name: "white-pawn", position: "28%,59%", size: "8%,8%", color: "white-pawn"},
{name: "white-pawn", position: "20%,63%", size: "8%,8%", color: "white-pawn"},
{name: "white-pawn", position: "12%,68%", size: "8%,8%", color: "white-pawn"}],

	questions: null, 
	
	mouseCoordsToolEnabled : true,
	piecePositionsToolEnabled: true
}
